name: Experiment
on: 
  pull_request:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: debug }
    - name: List files
      id: Experiment
      run: asdas
    - name: The job has failed
      if: ${{ failure() }}
      run: Echo job has failed ${{ failure() }}